### ISSUE TITLE
标点错误，格式错误，代码缩进（8.1,8.2,8.3节）

### ISSUE THREAD

**Issue by donggua2333** [xylinuxer/LKPA#15]
1.  8.1节：2处标点错误，1处格式错误
2.  8.2节：6处标点错误，6处格式错误， 1处代码缩进， 1处斜体转黑体
3.  8.3节：1处代码缩进

**Comment by zyfjeff** [comment]
@DennisWong  确定负责人 assign 给它，设置label，这种一般设置为 修正，milestone为第一阶段
